CREATE TABLE "Candidato" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" varchar,
  "last_name" varchar,
  "email" varchar UNIQUE,
  "cpf" varchar UNIQUE,
  "cep" varchar,
  "description" text,
  "password" varchar
);

CREATE TABLE "Empresa" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "description" text,
  "email" varchar UNIQUE,
  "cnpj" varchar,
  "cep" varchar,
  "country" varchar,
  "password" varchar
);

CREATE TABLE "Vaga" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "description" text,
  "city" varchar,
  "state" varchar(2),
  "empresa_id" int,
  "created_at" timestamp
);

CREATE TABLE "Candidato_Vaga" (
  "candidato_id" int,
  "vaga_id" int,
  PRIMARY KEY ("candidato_id", "vaga_id")
);

CREATE TABLE "Vaga_Competencia" (
  "vaga_id" int UNIQUE,
  "competencia_id" int UNIQUE,
  PRIMARY KEY ("vaga_id", "competencia_id")
);

CREATE TABLE "Competencia" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar
);

CREATE TABLE "Candidato_Competencia" (
  "candidato_id" int UNIQUE,
  "competencia_id" int UNIQUE,
  PRIMARY KEY ("candidato_id", "competencia_id")
);

CREATE TABLE "Match" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "empresa_id" int,
  "candidato_id" int
);

ALTER TABLE "Vaga" ADD FOREIGN KEY ("empresa_id") REFERENCES "Empresa" ("id");

ALTER TABLE "Candidato_Vaga" ADD FOREIGN KEY ("candidato_id") REFERENCES "Candidato" ("id");

ALTER TABLE "Candidato_Vaga" ADD FOREIGN KEY ("vaga_id") REFERENCES "Vaga" ("id");

ALTER TABLE "Vaga_Competencia" ADD FOREIGN KEY ("vaga_id") REFERENCES "Vaga" ("id");

ALTER TABLE "Vaga_Competencia" ADD FOREIGN KEY ("competencia_id") REFERENCES "Competencia" ("id");

ALTER TABLE "Candidato_Competencia" ADD FOREIGN KEY ("candidato_id") REFERENCES "Candidato" ("id");

ALTER TABLE "Candidato_Competencia" ADD FOREIGN KEY ("competencia_id") REFERENCES "Competencia" ("id");

ALTER TABLE "Match" ADD FOREIGN KEY ("empresa_id") REFERENCES "Empresa" ("id");

ALTER TABLE "Match" ADD FOREIGN KEY ("candidato_id") REFERENCES "Candidato" ("id");
